// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wycwyqxiozwjlutwypjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5Y3d5cXhpb3p3amx1dHd5cGp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5Nzc1MjksImV4cCI6MjA0OTU1MzUyOX0.lUgmKm8yd6WGf3LEgEmG5ASgS_Mf4g_xnBvMh_LLfdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);